@url = http://localhost:3000
@deletepost = 
@changepost = 
@singlepost = 659ee26d0b9e9ccfbf37c1c6
@date = "{{$datetime iso8601}}"
### 
//Return All blog posts
GET  {{url}}/api/v1/posts HTTP/1.1
###
//Return single blog post
GET {{url}}/api/v1/posts/{{singlepost}} HTTP/1.1
###
//Add new blog post
POST {{url}}/api/v1/posts HTTP/1.1
Content-Type: application/json

{
    "title": "Post 1",
    "description": "First post",
    "author": "Cyril",
    "published": true
}

###
//Delete
DELETE {{url}}/api/v1/posts/{{deletepost}} HTTP/1.1
###
//Update
PUT {{url}}/api/v1/posts/6599b1a233bbb7cd90029ed2 HTTP/1.1
Content-Type: application/json

{
  "title": "Changed title"
}