#Workflow is based on: https://github.com/BretFisher/docker-build-workflow.git
#But I have edited it for my needs.
#wokrflow will start everytime push & commit was made to main release branch and also start everytime if pull_request is made to main.
name: Docker Build and Dependencies

on:
    push:
        branches:
            - main
    pull_request:
#ENV Secrets...
env:
    MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
    MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          
jobs:
    #NEW JOB: (START) ##########################################################
    setup:
        name: Setup Node.js and install dependencies
        runs-on: ubuntu-latest
        steps:
           - name: Checkout code
             uses: actions/checkout@v3

           - name: Setup Node.js
             uses: actions/setup-node@v3
             with:
               node-version: 16

           - name: Setup pnpm
             uses: pnpm/action-setup@v2
             with:
              version: latest

           - name: Install dependencies
             run: pnpm install
    #NEW JOB: (END) ############################################################
    #NEW JOB: (START) ##########################################################          
    build-image:
        name: Build Images 
        runs-on: ubuntu-latest
        steps:

    # Login top Docker Hub account with secrets
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}


        # Login to Github Container Registry with Token
          - name: Login to GitHub Container Registry
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
        #Checkout your repository so this  workflow can access its contents
        #///The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2
        #use actions/checkout@v3 instead
          - name: Checkout code
            uses: actions/checkout@v3
            with:
                node-version: 16
                #1. pull mongo latest image before build No such image: mongo:latest
                #2. Run docker.compose.yaml file
                #3. tag the built docker image
                #4. push the built image to docker hub
          - name: Build and push MongoDB image
            run: |
              docker pull mongo:latest
              docker-compose build mongo
              docker tag mongo:latest ${{ secrets.DOCKERHUB_USERNAME }}/mongo:latest
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/mongo:latest
    #NEW JOB: (END) ############################################################
    #NEW JOB: (START) ##########################################################

    