name: Docker Build with QEMU 

on:
    push:
        branches:
            - main
    pull_request:
env:
    MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
    MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          
jobs:
    setup:
        name: Setup Node.js and install dependencies
        runs-on: ubuntu-latest
        steps:
           - name: Checkout code
             uses: actions/checkout@v3

           - name: Setup Node.js
             uses: actions/setup-node@v3
             with:
               node-version: 16

            #Use caching if available..
           - name: Setup pnpm
             uses: pnpm/action-setup@v2
             with:
              version: latest
              cache: 'pnpm'
              cache-dependency-path: ./FullDevLekce12/ppnpm-lock.yaml

           - name: Install dependencies
             run: pnpm install
          
    build-image:
        name: Build Images 
        runs-on: ubuntu-latest
        steps:
            #QEMU SETUP
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3

            #Default builder
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Login to GitHub Container Registry
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GHR_TOKEN }}

          - name: Checkout code
            uses: actions/checkout@v3
            with:
                node-version: 16

          - name: Build and push MongoDB image
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: ${{ secrets.DOCKERHUB_USERNAME }}/mongo:latest
              build-args: |
                MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
                MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
              platforms: linux/amd64,linux/arm64,linux/arm/v7
              #QEMU multiplatform...